# Generated by Django 5.2.7 on 2025-11-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_obudozer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmrecord',
            name='exist',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vmrecord',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vmrecord',
            name='vcenter_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
